# Site settings
title: Clinica Alvessa
email: patriciogtrz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "alvessa.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
